#!/usr/bin/env python3
"""Convert the game's leitmotif note tables (tools/themes_js.json, made by
make_themes.py) into SID note data for the C64 port.

Each note becomes 3 bytes: SID freq lo, freq hi, duration in PAL frames.
freq 0/0 = rest.  A 0,0,0 triplet terminates a song (the player loops).
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "..", "tools", "themes_js.json")
OUT = os.path.join(HERE, "..", "build", "music.inc")

PAL_CLOCK = 985248.0
SID_SCALE = 16777216.0 / PAL_CLOCK  # freq register units per Hz


def sid_freq(midi):
    hz = 440.0 * 2 ** ((midi - 69) / 12)
    reg = round(hz * SID_SCALE)
    return min(reg, 0xFFFF)


def song(notes):
    rows = []
    for midi, dur60 in notes:
        dur = max(2, min(255, round(dur60 * 5 / 6)))  # 60 Hz -> 50 Hz PAL
        reg = sid_freq(midi) if midi else 0
        rows.append((reg & 0xFF, reg >> 8, dur))
    rows.append((0, 0, 0))  # terminator -> loop
    return rows


def main():
    themes = json.load(open(SRC))
    with open(OUT, "w") as f:
        f.write("; generated by gen_music.py - do not edit\n")
        for label, key in (("songPeterData", "peter"), ("songWolfData", "wolf")):
            rows = song(themes[key]["notes"])
            f.write(f"{label}\n")
            for lo, hi, dur in rows:
                f.write(f"\tdc.b ${lo:02x},${hi:02x},${dur:02x}\n")
            print(f"{label}: {len(rows)-1} notes")


if __name__ == "__main__":
    main()
