#!/usr/bin/env python3
"""Convert the ASCII sprite/char art in art/ into dasm include files in build/.

Sprites: 12x21 pixel-pairs, multicolor. . =%00  K=%01  C=%10  W=%11
Chars:   8x8 hires bitmaps, # = set.
A sprite header may say `mirror <name>` to also emit a horizontally
flipped copy (pixel-pair order reversed per row) right after it.
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ART = os.path.join(HERE, "..", "art")
OUT = os.path.join(HERE, "..", "build")

PAIR = {".": 0b00, "K": 0b01, "C": 0b10, "W": 0b11}


def parse_blocks(path, header_words, rows):
    """Yield (header_word, header_tokens, list_of_row_strings)."""
    blocks, cur, tokens, word = [], None, None, None
    with open(path, encoding="utf-8") as f:
        for raw in f:
            line = raw.rstrip("\n")
            if line.startswith(";") or not line.strip():
                continue
            first = line.split()[0]
            if first in header_words:
                if cur is not None:
                    blocks.append((word, tokens, cur))
                word, tokens, cur = first, line.split()[1:], []
            else:
                if cur is None:
                    sys.exit(f"{path}: art row before any header: {line!r}")
                cur.append(line)
    if cur is not None:
        blocks.append((word, tokens, cur))
    for word, tokens, art in blocks:
        if len(art) != rows:
            sys.exit(f"{path}: block '{' '.join(tokens)}' has {len(art)} rows, expected {rows}")
    return blocks


def sprite_bytes(art):
    out = []
    for row in art:
        if len(row) != 12:
            sys.exit(f"sprite row is {len(row)} wide, expected 12: {row!r}")
        bits = 0
        for c in row:
            bits = (bits << 2) | PAIR[c]
        out += [(bits >> 16) & 0xFF, (bits >> 8) & 0xFF, bits & 0xFF]
    out.append(0)  # pad to 64 bytes
    return out


def mirror_rows(art):
    """Horizontally flip pixel-pair art (works for any width)."""
    return [row[::-1] for row in art]


def char_bytes(art):
    out = []
    for row in art:
        if len(row) != 8:
            sys.exit(f"char row is {len(row)} wide, expected 8: {row!r}")
        b = 0
        for c in row:
            b = (b << 1) | (1 if c == "#" else 0)
        out.append(b)
    return out


def dcb(data, per_line=21):
    lines = []
    for i in range(0, len(data), per_line):
        chunk = ",".join(f"${b:02x}" for b in data[i:i + per_line])
        lines.append(f"\tdc.b {chunk}")
    return "\n".join(lines)


def main():
    os.makedirs(OUT, exist_ok=True)

    # ---- sprites ----
    # `sprite <name> [mirror <name2>]`      12-wide, one hardware sprite
    # `wide <name> [mirror <name2>]`        24-wide, split into _a + _b halves
    parts = []

    def emit(name, art):
        parts.append(f"spr_{name}\n{dcb(sprite_bytes(art))}")

    for word, tokens, art in parse_blocks(os.path.join(ART, "sprites.txt"),
                                          ("sprite", "wide"), 21):
        name = tokens[0]
        mirror = tokens[2] if len(tokens) >= 3 and tokens[1] == "mirror" else None
        if word == "sprite":
            emit(name, art)
            if mirror:
                emit(mirror, mirror_rows(art))
        else:  # wide: left half then right half, then the mirrored pair
            emit(name + "_a", [r[:12] for r in art])
            emit(name + "_b", [r[12:] for r in art])
            if mirror:
                m = mirror_rows(art)
                emit(mirror + "_a", [r[:12] for r in m])
                emit(mirror + "_b", [r[12:] for r in m])
    # frames 0-15 live at $2000 (pointers $80-$8f, up against the HUD
    # block at $2400); everything after goes to $2540 (pointers $95+)
    with open(os.path.join(OUT, "sprites.inc"), "w") as f:
        f.write("; generated by gen_assets.py - do not edit\n" + "\n".join(parts[:16]) + "\n")
    assert len(parts) - 16 <= 27, f"sprites2 overflows into SCREENB: {len(parts)-16} frames"
    with open(os.path.join(OUT, "sprites2.inc"), "w") as f:
        f.write("; generated by gen_assets.py - do not edit\n" + "\n".join(parts[16:]) + "\n")

    # ---- chars ----
    blocks = [(t, a) for _, t, a in
              parse_blocks(os.path.join(ART, "chars.txt"), ("char",), 8)]
    codes = [int(t[0]) for t, _ in blocks]
    if codes != list(range(codes[0], codes[0] + len(codes))):
        sys.exit(f"char codes must be contiguous, got {codes}")
    data = []
    for _, art in blocks:
        data += char_bytes(art)
    with open(os.path.join(OUT, "chars.inc"), "w") as f:
        f.write("; generated by gen_assets.py - do not edit\n")
        f.write(f"CHAR_FIRST equ {codes[0]}\n")
        f.write(f"CHAR_COUNT equ {len(codes)}\n")
        f.write(f"charData\n{dcb(data, per_line=8)}\n")

    print(f"sprites.inc: 16 frames + sprites2.inc: {len(parts)-16} frames   "
          f"chars.inc: {len(codes)} chars (codes {codes[0]}..{codes[-1]})")


if __name__ == "__main__":
    main()
