#!/usr/bin/env python3
"""Convert the ASCII sprite/char art in art/ into dasm include files in build/.

Sprites: 12x21 pixel-pairs, multicolor. . =%00  K=%01  C=%10  W=%11
Chars:   8x8 hires bitmaps, # = set.
A sprite header may say `mirror <name>` to also emit a horizontally
flipped copy (pixel-pair order reversed per row) right after it.
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ART = os.path.join(HERE, "..", "art")
OUT = os.path.join(HERE, "..", "build")

PAIR = {".": 0b00, "K": 0b01, "C": 0b10, "W": 0b11}


def parse_blocks(path, header_word, rows):
    """Yield (header_tokens, list_of_row_strings)."""
    blocks, cur, tokens = [], None, None
    with open(path, encoding="utf-8") as f:
        for raw in f:
            line = raw.rstrip("\n")
            if line.startswith(";") or not line.strip():
                continue
            if line.startswith(header_word + " "):
                if cur is not None:
                    blocks.append((tokens, cur))
                tokens, cur = line.split()[1:], []
            else:
                if cur is None:
                    sys.exit(f"{path}: art row before any '{header_word}' header: {line!r}")
                cur.append(line)
    if cur is not None:
        blocks.append((tokens, cur))
    for tokens, art in blocks:
        if len(art) != rows:
            sys.exit(f"{path}: block '{' '.join(tokens)}' has {len(art)} rows, expected {rows}")
    return blocks


def sprite_bytes(art, mirrored=False):
    out = []
    for row in art:
        if len(row) != 12:
            sys.exit(f"sprite row is {len(row)} wide, expected 12: {row!r}")
        pairs = [PAIR[c] for c in row]
        if mirrored:
            pairs.reverse()
        bits = 0
        for p in pairs:
            bits = (bits << 2) | p
        out += [(bits >> 16) & 0xFF, (bits >> 8) & 0xFF, bits & 0xFF]
    out.append(0)  # pad to 64 bytes
    return out


def char_bytes(art):
    out = []
    for row in art:
        if len(row) != 8:
            sys.exit(f"char row is {len(row)} wide, expected 8: {row!r}")
        b = 0
        for c in row:
            b = (b << 1) | (1 if c == "#" else 0)
        out.append(b)
    return out


def dcb(data, per_line=21):
    lines = []
    for i in range(0, len(data), per_line):
        chunk = ",".join(f"${b:02x}" for b in data[i:i + per_line])
        lines.append(f"\tdc.b {chunk}")
    return "\n".join(lines)


def main():
    os.makedirs(OUT, exist_ok=True)

    # ---- sprites ----
    parts = []
    for tokens, art in parse_blocks(os.path.join(ART, "sprites.txt"), "sprite", 21):
        name = tokens[0]
        parts.append(f"spr_{name}\n{dcb(sprite_bytes(art))}")
        if len(tokens) >= 3 and tokens[1] == "mirror":
            parts.append(f"spr_{tokens[2]}\n{dcb(sprite_bytes(art, mirrored=True))}")
    with open(os.path.join(OUT, "sprites.inc"), "w") as f:
        f.write("; generated by gen_assets.py - do not edit\n" + "\n".join(parts) + "\n")

    # ---- chars ----
    blocks = parse_blocks(os.path.join(ART, "chars.txt"), "char", 8)
    codes = [int(t[0]) for t, _ in blocks]
    if codes != list(range(codes[0], codes[0] + len(codes))):
        sys.exit(f"char codes must be contiguous, got {codes}")
    data = []
    for _, art in blocks:
        data += char_bytes(art)
    with open(os.path.join(OUT, "chars.inc"), "w") as f:
        f.write("; generated by gen_assets.py - do not edit\n")
        f.write(f"CHAR_FIRST equ {codes[0]}\n")
        f.write(f"CHAR_COUNT equ {len(codes)}\n")
        f.write(f"charData\n{dcb(data, per_line=8)}\n")

    print(f"sprites.inc: {len(parts)} frames   chars.inc: {len(codes)} chars "
          f"(codes {codes[0]}..{codes[-1]})")


if __name__ == "__main__":
    main()
