#!/usr/bin/env python3
"""Convert the leitmotif note tables (tools/themes_js.json) into YM2151
note streams for the X16 port.

Each note: .byte KC, DUR   (KC = YM2151 key code, DUR in 60 Hz frames)
KC $FE = rest, $FF = end of song (player loops).
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "..", "tools", "themes_js.json")
OUT = os.path.join(HERE, "..", "build", "music.inc")

# semitones above C# -> YM2151 note code
KCNOTE = [0, 1, 2, 4, 5, 6, 8, 9, 10, 12, 13, 14]

SONGS = ["peter", "duck", "bird", "cat", "grandfather", "wolf", "hunters"]

def kc(midi):
    n = midi - 61                      # C#4 = KC octave 4, note 0
    octave = 4 + n // 12
    octave = max(0, min(7, octave))
    return (octave << 4) | KCNOTE[n % 12]

def main():
    themes = json.load(open(SRC))
    L = ["; generated by gen_music.py - do not edit"]
    ptrs = []
    for name in SONGS:
        notes = themes[name]["notes"]
        label = f"song_{name}"
        ptrs.append(label)
        L.append(f"{label}:")
        rows = []
        for midi, dur in notes:
            d = max(2, min(255, int(round(dur))))
            rows.append((kc(midi) if midi else 0xFE, d))
        body = ",".join(f"${a:02X},${b:02X}" for a, b in rows)
        for i in range(0, len(rows), 12):
            chunk = rows[i:i+12]
            L.append("\t.byte " + ",".join(f"${a:02X},${b:02X}" for a, b in chunk))
        L.append("\t.byte $FF")
    L.append("songPtrLo: .byte " + ",".join(f"<{p}" for p in ptrs))
    L.append("songPtrHi: .byte " + ",".join(f">{p}" for p in ptrs))
    L.append(f"SONG_COUNT = {len(ptrs)}")
    for i, name in enumerate(SONGS):
        L.append(f"SONG_{name.upper()} = {i}")
    with open(OUT, "w") as f:
        f.write("\n".join(L) + "\n")
    print("music.inc:", ", ".join(f"{n}({len(themes[n]['notes'])})" for n in SONGS))

if __name__ == "__main__":
    main()
