#!/usr/bin/env python3
"""Convert peterstartup.png into an X16 VERA bitmap startup screen.

Output (build/):
    SPLASH.BIN     2-byte $0000 header + 320x240 8bpp indices -> VRAM $00000
    splash.inc     splashPal: 512 bytes, 256 VERA palette entries (GB,0R)
    AUTOBOOT.X16   tokenized BASIC stub: LOAD the poster into VRAM (the
                   KERNAL's VRAM load, which works on SD and Host FS alike),
                   mark golden RAM, then chain-load PETER.PRG
    splash_preview.png   eyeball render of exactly what VERA will show

The portrait poster is fit to 240 px tall and pillar-boxed (black bars) into
the 320x240 landscape frame, then median-cut quantized to 256 colours and
each channel crushed to VERA's 4 bits.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
X16 = os.path.join(HERE, "..")
SRC = os.path.join(X16, "..", "peterstartup.png")
OUT = os.path.join(X16, "build")

W, H = 320, 240


def main():
    from PIL import Image
    os.makedirs(OUT, exist_ok=True)

    im = Image.open(SRC).convert("RGB")
    # fit to full height, pillar-box into 320x240
    tw = max(1, round(H * im.width / im.height))
    tw = min(tw, W)
    fitted = im.resize((tw, H), Image.LANCZOS)
    canvas = Image.new("RGB", (W, H), (0, 0, 0))
    canvas.paste(fitted, ((W - tw) // 2, 0))

    # 256-colour median cut, then crush the palette to 4 bits/channel
    q = canvas.quantize(colors=256, method=Image.MEDIANCUT, dither=Image.NONE)
    pal = q.getpalette()[: 256 * 3]
    idx = bytes(q.getdata())            # one index per pixel, 320*240

    # 4-bit palette
    pal4 = []
    for i in range(256):
        r, g, b = pal[i * 3], pal[i * 3 + 1], pal[i * 3 + 2]
        pal4.append((r >> 4, g >> 4, b >> 4))

    # ---- SPLASH.BIN : 2-byte header + indices ----
    # LOAD"...",8,2 loads into VRAM: the header supplies the low 16 bits of
    # the address ($0000) and SA-2 the upper bits (0) -> lands at $00000.
    with open(os.path.join(OUT, "SPLASH.BIN"), "wb") as f:
        f.write(b"\x00\x00")
        f.write(idx)

    # ---- AUTOBOOT.X16 : tokenized BASIC chain-loader ----
    #   10 VLOAD"SPLASH.BIN",8,0,0   poster pixels -> VRAM $00000 (skips header)
    #   20 POKE1024,80:POKE1025,87   golden-RAM marker "PW": poster present
    #   30 LOAD"PETER.PRG",8,1       chain-load; BASIC re-runs it (SYS stub)
    # Tokens: VLOAD=$CE$85 (X16 two-byte token), POKE=$97, LOAD=$93.
    def basline(num, tokens):
        return num.to_bytes(2, "little") + tokens + b"\x00"

    lines = [
        basline(10, b'\xce\x85"SPLASH.BIN",8,0,0'),
        basline(20, b"\x971024,80:\x971025,87"),
        basline(30, b'\x93"PETER.PRG",8,1'),
    ]
    addr = 0x0801
    prog = bytearray()
    for ln in lines:
        addr += 2 + len(ln)
        prog += addr.to_bytes(2, "little") + ln
    prog += b"\x00\x00"
    with open(os.path.join(OUT, "AUTOBOOT.X16"), "wb") as f:
        f.write(b"\x01\x08")
        f.write(prog)

    # ---- splash.inc : VERA palette (byte0 = GB, byte1 = 0R) ----
    pbytes = bytearray()
    for r, g, b in pal4:
        pbytes.append((g << 4) | b)
        pbytes.append(r)
    L = ["; generated by gen_splash.py - do not edit", ".rodata", "splashPal:"]
    for i in range(0, len(pbytes), 16):
        L.append("\t.byte " + ",".join(f"${b:02X}" for b in pbytes[i:i + 16]))
    with open(os.path.join(OUT, "splash.inc"), "w") as f:
        f.write("\n".join(L) + "\n")

    # ---- preview : what VERA will actually display ----
    prev = Image.new("RGB", (W, H))
    ppx = prev.load()
    rgb8 = [(r * 17, g * 17, b * 17) for r, g, b in pal4]
    for y in range(H):
        for x in range(W):
            ppx[x, y] = rgb8[idx[y * W + x]]
    prev.save(os.path.join(OUT, "splash_preview.png"))

    print(f"SPLASH.BIN {len(idx)} bytes ({W}x{H} 8bpp), palette 256 -> splash.inc")


if __name__ == "__main__":
    main()
